# -*- coding: utf-8 -*-
"""4th

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ozD2_LU3rVSp-FacTGIcMZWIsT4trH5
"""

import pandas as pd

# Creating the DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [45, 50, 38, 60, 55],
    "Cholesterol": [200, 220, 180, 250, 230]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)